// Contract test: the Node reducer must agree with the Rust-generated
// summary for the shared fixture session (generated by router-headless
// against the firmware simulator with injected faults).

import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { readEvents } from '../lib/ndjson.js';
import { reduce } from '../lib/reduce.js';
import { bucketize } from '../lib/bucketize.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const fixtures = path.join(here, 'fixtures');

function fixtureSession() {
  const files = fs.readdirSync(fixtures);
  const ndjson = files.filter((f) => f.endsWith('.ndjson')).map((f) => path.join(fixtures, f));
  const summaryFile = files.find((f) => f.endsWith('.summary.json'));
  const rustSummary = JSON.parse(fs.readFileSync(path.join(fixtures, summaryFile), 'utf8'));
  return { ndjson, rustSummary };
}

test('reducer totals match the Rust summary', async () => {
  const { ndjson, rustSummary } = fixtureSession();
  const reduced = await reduce(readEvents(ndjson));

  // the reducer trusts session_end totals, so these must match exactly
  assert.deepEqual(reduced.totals, rustSummary.totals);
  assert.equal(reduced.session.clean_exit, rustSummary.session.clean_exit);
  assert.equal(reduced.session.host, rustSummary.session.host);
});

test('reducer rebuilds per-column counters from bus_stats', async () => {
  const { ndjson, rustSummary } = fixtureSession();
  const reduced = await reduce(readEvents(ndjson));

  assert.equal(reduced.columns.length, rustSummary.columns.length);
  for (const rustColumn of rustSummary.columns) {
    const nodeColumn = reduced.columns.find((c) => c.col === rustColumn.col);
    assert.ok(nodeColumn, `column ${rustColumn.col} present`);
    assert.equal(nodeColumn.timeouts, rustColumn.timeouts, `col ${rustColumn.col} timeouts`);
    assert.equal(nodeColumn.cobs_errors, rustColumn.cobs_errors, `col ${rustColumn.col} cobs`);
    // bus_stats windows flush every 10 s; the final partial window is only
    // in the Rust cumulative counters, so allow a small shortfall
    assert.ok(
      nodeColumn.tx <= rustColumn.tx && nodeColumn.tx >= rustColumn.tx * 0.7,
      `col ${rustColumn.col} tx ${nodeColumn.tx} ~ ${rustColumn.tx}`
    );
  }
});

test('reducer identifies the same faulty units', async () => {
  const { ndjson, rustSummary } = fixtureSession();
  const reduced = await reduce(readEvents(ndjson));

  const key = (p) => `${p.col}/${p.portal}`;
  const rustFaulty = new Set(
    rustSummary.portals
      .filter((p) => ['faulty', 'silent'].includes(p.final_state))
      .map(key)
  );
  const nodeFaulty = new Set(
    reduced.portals.filter((p) => ['faulty', 'silent'].includes(p.final_state)).map(key)
  );
  assert.deepEqual(nodeFaulty, rustFaulty);
  // the injected dead portals must be flagged
  assert.ok(rustFaulty.size > 0, 'fixture contains faulty units');
});

test('fault timeline merges consecutive faults', async () => {
  const { ndjson } = fixtureSession();
  const reduced = await reduce(readEvents(ndjson));

  assert.ok(reduced.fault_timeline.length > 0);
  const totalFaults = reduced.fault_timeline.reduce((total, f) => total + f.count, 0);
  assert.ok(
    totalFaults >= reduced.fault_timeline.length,
    'merged spans carry counts'
  );
  for (const span of reduced.fault_timeline) {
    assert.ok(span.ts_end >= span.ts);
    assert.ok(typeof span.type === 'string');
  }
});

test('bucketize produces columnar series', async () => {
  const { ndjson } = fixtureSession();
  const timeline = await bucketize(readEvents(ndjson), 10_000);

  assert.ok(timeline.t.length >= 3, 'several buckets');
  assert.equal(timeline.t.length, timeline.tx.length);
  assert.equal(timeline.t.length, timeline.faults.length);
  assert.ok(timeline.faults.some((f) => f > 0), 'faults visible in the timeline');
});
