"""Stamp src/Version.h with a build identity, before every build.

The string this writes ends up in two places that matter: the banner Logger prints over RS485, and
the `version` field App reports to the Router. It is also what PortalFlasher scrapes straight out
of a flash readback to say what a board is running -- no symbols, no ELF, just the ASCII sitting
in the image.

# Why a git commit and not only a timestamp

A timestamp says *when* a binary was built. It does not say *what* was built, and those are
different questions the moment two people build, or the moment someone asks which commit is on a
board that came back from site. The commit answers it; the timestamp then distinguishes rebuilds
of the same commit.

The `+` suffix is the important half. A build from a dirty tree is not reproducible from its
commit, and marking it is the difference between "this board runs 3f9a1c2" and "this board runs
something that resembled 3f9a1c2 on someone's laptop".

# Why Version.h is not in git

It used to be, and every build rewrote it, so every build dirtied the tree -- which then made the
next build stamp itself dirty, permanently, for a reason that had nothing to do with the source.
It is generated, so it is ignored and written here if absent.
"""

Import("env")

import subprocess
from datetime import datetime
from pathlib import Path

# `__file__` is not defined here: PlatformIO `exec`s this script rather than importing it, so the
# module globals a normal script relies on are absent. PROJECT_DIR is what the builder provides,
# and it is correct regardless of where pio was invoked from.
HERE = Path(env["PROJECT_DIR"])


def git(*args, default=""):
    """Run a git command against this working tree, or give up quietly.

    A build must not fail because the tree was exported as a zip, or because git is not on PATH.
    An unknown commit is a worse build stamp than a known one and a better outcome than no
    firmware.
    """
    try:
        out = subprocess.run(
            ["git", *args],
            cwd=str(HERE),
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return default
    return out.stdout.strip() if out.returncode == 0 else default


commit = git("rev-parse", "--short=7", "HEAD", default="nogit")

# `--porcelain` over the whole tree, not just PortalFW: a change in the msgpack submodule or in a
# build script changes the firmware just as surely as a change in src/.
dirty = "+" if git("status", "--porcelain") else ""

time_string = datetime.now().strftime("%Y-%m-%d_%H.%M")
version_string = "Portal v%s %s%s" % (time_string, commit, dirty)

define_string = '#define PORTAL_VERSION_STRING "' + version_string + '"'
print(define_string)

header = HERE / "src" / "Version.h"
header.write_text(
    "// Generated by set_build_date.py before every build. Not tracked in git.\n"
    + define_string
    + "\n",
    encoding="utf-8",
)
